"""The blocks in items.png."""

import Block

__author__ = "Alex Cappiello"
__license__ = "See LICENSE.txt"


def item_block(name):
    """All item blocks are 1x1."""
    return Block.BlockInfo(name, 1, 1)


# Naming conventions are done with the following considerations:
#   - No spaces (underscores instead).
#   - All lowercase.
#   - Similar items are grouped when sorted by name (influences word order).
items_map = {
    ( 0,  0) : item_block("helmet_leather"),
    ( 0,  1) : item_block("helmet_chain"),
    ( 0,  2) : item_block("helmet_iron"),
    ( 0,  3) : item_block("helmet_diamond"),
    ( 0,  4) : item_block("helmet_gold"),
    ( 0,  5) : item_block("flint_steel"),
    ( 0,  6) : item_block("flint"),
    ( 0,  7) : item_block("coal"),
    ( 0,  8) : item_block("string"),
    ( 0,  9) : item_block("seeds_wheat"),
    ( 0, 10) : item_block("apple"),
    ( 0, 11) : item_block("apple_gold"),
    ( 0, 12) : item_block("egg"),
    ( 0, 13) : item_block("sugar"),
    ( 0, 14) : item_block("snowball"),
    ( 0, 15) : item_block("head"),
    ( 1,  0) : item_block("chestplate_leather"),
    ( 1,  1) : item_block("chestplate_chain"),
    ( 1,  2) : item_block("chestplate_iron"),
    ( 1,  3) : item_block("chestplate_diamond"),
    ( 1,  4) : item_block("chestplate_gold"),
    ( 1,  5) : item_block("bow"),
    ( 1,  6) : item_block("brick"),
    ( 1,  7) : item_block("ingot_iron"),
    ( 1,  8) : item_block("feather"),
    ( 1,  9) : item_block("wheat"),
    ( 1, 10) : item_block("painting"),
    ( 1, 11) : item_block("sugar_canes"),
    ( 1, 12) : item_block("bone"),
    ( 1, 13) : item_block("cake"),
    ( 1, 14) : item_block("slimeball"),
    ( 1, 15) : item_block("chest"),
    ( 2,  0) : item_block("leggings_leather"),
    ( 2,  1) : item_block("leggings_chain"),
    ( 2,  2) : item_block("leggings_iron"),
    ( 2,  3) : item_block("leggings_diamond"),
    ( 2,  4) : item_block("leggings_gold"),
    ( 2,  5) : item_block("arrow"),
    ( 2,  6) : item_block("quiver_(unused)"),
    ( 2,  7) : item_block("ingot_gold"),
    ( 2,  8) : item_block("gunpowder"),
    ( 2,  9) : item_block("bread"),
    ( 2, 10) : item_block("sign"),
    ( 2, 11) : item_block("door_wooden"),
    ( 2, 12) : item_block("door_iron"),
    ( 2, 13) : item_block("bed"),
    ( 2, 14) : item_block("fire_charge"),
    ( 2, 15) : item_block("legs"),
    ( 3,  0) : item_block("boots_leather"),
    ( 3,  1) : item_block("boots_chain"),
    ( 3,  2) : item_block("boots_iron"),
    ( 3,  3) : item_block("boots_diamond"),
    ( 3,  4) : item_block("boots_gold"),
    ( 3,  5) : item_block("stick"),
    ( 3,  6) : item_block("compass"),
    ( 3,  7) : item_block("diamond"),
    ( 3,  8) : item_block("redstone"),
    ( 3,  9) : item_block("clay"),
    ( 3, 10) : item_block("paper"),
    ( 3, 11) : item_block("book"),
    ( 3, 12) : item_block("map_filled"),
    ( 3, 13) : item_block("seeds_pumpkin"),
    ( 3, 14) : item_block("seeds_melon"),
    ( 3, 15) : item_block("feet"),
    ( 4,  0) : item_block("sword_wooden"),
    ( 4,  1) : item_block("sword_stone"),
    ( 4,  2) : item_block("sword_iron"),
    ( 4,  3) : item_block("sword_diamond"),
    ( 4,  4) : item_block("sword_gold"),
    ( 4,  5) : item_block("fishing_pole"),
    ( 4,  6) : item_block("clock"),
    ( 4,  7) : item_block("bowl"),
    ( 4,  8) : item_block("mushroom_stew"),
    ( 4,  9) : item_block("glowstone_dust"),
    ( 4, 10) : item_block("bucket"),
    ( 4, 11) : item_block("bucket_water"),
    ( 4, 12) : item_block("bucket_lava"),
    ( 4, 13) : item_block("bucket_milk"),
    ( 4, 14) : item_block("dye_ink_sack"),
    ( 4, 15) : item_block("dye_gray"),
    ( 5,  0) : item_block("shovel_wooden"),
    ( 5,  1) : item_block("shovel_stone"),
    ( 5,  2) : item_block("shovel_iron"),
    ( 5,  3) : item_block("shovel_diamond"),
    ( 5,  4) : item_block("shovel_gold"),
    ( 5,  5) : item_block("unknown_2"),
    ( 5,  6) : item_block("redstone_repeater"),
    ( 5,  7) : item_block("pork_raw"),
    ( 5,  8) : item_block("pork_cooked"),
    ( 5,  9) : item_block("fish_raw"),
    ( 5, 10) : item_block("fish_cooked"),
    ( 5, 11) : item_block("zombie_flesh"),
    ( 5, 12) : item_block("cookie"),
    ( 5, 13) : item_block("shears"),
    ( 5, 14) : item_block("dye_rose_red"),
    ( 5, 15) : item_block("dye_pink"),
    ( 6,  0) : item_block("pickaxe_wooden"),
    ( 6,  1) : item_block("pickaxe_stone"),
    ( 6,  2) : item_block("pickaxe_iron"),
    ( 6,  3) : item_block("pickaxe_diamond"),
    ( 6,  4) : item_block("pickaxe_gold"),
    ( 6,  5) : item_block("bow_stretch_1"),
    ( 6,  6) : item_block("carrot_on_stick"),
    ( 6,  7) : item_block("leather"),
    ( 6,  8) : item_block("saddle"),
    ( 6,  9) : item_block("beef_raw"),
    ( 6, 10) : item_block("beef_cooked"),
    ( 6, 11) : item_block("ender_pearl"),
    ( 6, 12) : item_block("blaze_rod"),
    ( 6, 13) : item_block("melon"),
    ( 6, 14) : item_block("dye_cactus_green"),
    ( 6, 15) : item_block("dye_lime"),
    ( 7,  0) : item_block("axe_wooden"),
    ( 7,  1) : item_block("axe_stone"),
    ( 7,  2) : item_block("axe_iron"),
    ( 7,  3) : item_block("axe_diamond"),
    ( 7,  4) : item_block("axe_gold"),
    ( 7,  5) : item_block("bow_stretch_2"),
    ( 7,  6) : item_block("potato_baked"),
    ( 7,  7) : item_block("potato"),
    ( 7,  8) : item_block("carrots"),
    ( 7,  9) : item_block("chicken_raw"),
    ( 7, 10) : item_block("chicken_cooked"),
    ( 7, 11) : item_block("ghast_tear"),
    ( 7, 12) : item_block("gold_nugget"),
    ( 7, 13) : item_block("nether_wart"),
    ( 7, 14) : item_block("cocoa_beans"),
    ( 7, 15) : item_block("dye_yellow"),
    ( 8,  0) : item_block("hoe_wooden"),
    ( 8,  1) : item_block("hoe_stone"),
    ( 8,  2) : item_block("hoe_iron"),
    ( 8,  3) : item_block("hoe_diamond"),
    ( 8,  4) : item_block("hoe_gold"),
    ( 8,  5) : item_block("bow_stretch_3"),
    ( 8,  6) : item_block("potato_poisoned"),
    ( 8,  7) : item_block("minecart"),
    ( 8,  8) : item_block("boat"),
    ( 8,  9) : item_block("melon_glistening"),
    ( 8, 10) : item_block("spider_eye_fermented"),
    ( 8, 11) : item_block("spider_eye"),
    ( 8, 12) : item_block("glass_bottle"),
    ( 8, 13) : item_block("unknown_3"),
    ( 8, 14) : item_block("lapis_lazuli"),
    ( 8, 15) : item_block("dye_light_blue"),
    ( 9,  6) : item_block("carrot_golden"),
    ( 9,  7) : item_block("minecart_chest"),
    ( 9,  8) : item_block("pumpkin_pie"),
    ( 9,  9) : item_block("dragon_egg"),
    ( 9, 10) : item_block("splash_potion_bottle"),
    ( 9, 11) : item_block("ender_eye"),
    ( 9, 12) : item_block("cauldron"),
    ( 9, 13) : item_block("blaze_powder"),
    ( 9, 14) : item_block("dye_purple"),
    ( 9, 15) : item_block("dye_magenta"),
    (10,  7) : item_block("minecart_furnace"),
    (10,  9) : item_block("unknown_4"),
    (10, 10) : item_block("ruby_(unused)"),
    (10, 11) : item_block("bottle_o_enchanting"),
    (10, 12) : item_block("brewing_stand"),
    (10, 13) : item_block("magma_cream"),
    (10, 14) : item_block("dye_cyan"),
    (10, 15) : item_block("dye_brown"),
    (11,  9) : item_block("nether_star"),
    (11, 10) : item_block("emerald"),
    (11, 11) : item_block("book_quill"),
    (11, 12) : item_block("book_written"),
    (11, 13) : item_block("flower_pot"),
    (11, 14) : item_block("dye_light_gray"),
    (11, 15) : item_block("bone_meal"),
    (12, 13) : item_block("unknown_6"),
    (12,  9) : item_block("firework_rocket"),
    (12, 10) : item_block("firework_star"),
    (12, 13) : item_block("map_blank"),
    (12, 14) : item_block("item_frame"),
    (12, 15) : item_block("book_enchanted"),
    (14,  0) : item_block("skull_skeleton"),
    (14,  1) : item_block("skull_wither_skeleton"),
    (14,  2) : item_block("head_zombie"),
    (14,  3) : item_block("head"),
    (14,  4) : item_block("head_creeper"),
    (15,  0) : item_block("record_01"),
    (15,  1) : item_block("record_02"),
    (15,  2) : item_block("record_03"),
    (15,  3) : item_block("record_04"),
    (15,  4) : item_block("record_05"),
    (15,  5) : item_block("record_06"),
    (15,  6) : item_block("record_07"),
    (15,  7) : item_block("record_08"),
    (15,  8) : item_block("record_09"),
    (15,  9) : item_block("record_10"),
    (15, 10) : item_block("record_11"),
    (15, 11) : item_block("record_12"),
    (15, 12) : item_block("record_13"),
    (15, 13) : item_block("record_14"),
    (15, 14) : item_block("record_15"),
    (15, 15) : item_block("record_16")
    }
