import Block

terrain_map = {
    ( 0,  0) : Block.BlockInfo("grass", 1, 1),
    ( 0,  1) : Block.BlockInfo("stone", 1, 1),
    ( 0,  2) : Block.BlockInfo("dirt", 1, 1),
    ( 0,  3) : Block.BlockInfo("dirt_grass", 1, 1),
    ( 0,  4) : Block.BlockInfo("planks_oak", 1, 1),
    ( 0,  5) : Block.BlockInfo("stone_slab_side", 1, 1),
    ( 0,  6) : Block.BlockInfo("stone_slab_top", 1, 1),
    ( 0,  7) : Block.BlockInfo("bricks", 1, 1),
    ( 0,  8) : Block.BlockInfo("tnt_side", 1, 1),
    ( 0,  9) : Block.BlockInfo("tnt_top", 1, 1),
    ( 0, 10) : Block.BlockInfo("tnt_bottom", 1, 1),
    ( 0, 11) : Block.BlockInfo("web", 1, 1),
    ( 0, 12) : Block.BlockInfo("flower_red", 1, 1),
    ( 0, 13) : Block.BlockInfo("flower_yellow", 1, 1),
    ( 0, 15) : Block.BlockInfo("sapling_oak", 1, 1),
    ( 1,  0) : Block.BlockInfo("cobblestone", 1, 1),
    ( 1,  1) : Block.BlockInfo("bedrock", 1, 1),
    ( 1,  2) : Block.BlockInfo("sand", 1, 1),
    ( 1,  3) : Block.BlockInfo("gravel", 1, 1),
    ( 1,  4) : Block.BlockInfo("wood_side_oak", 1, 1),
    ( 1,  5) : Block.BlockInfo("wood_top_oak", 1, 1),
    ( 1,  6) : Block.BlockInfo("block_iron", 1, 1),
    ( 1,  7) : Block.BlockInfo("block_gold", 1, 1),
    ( 1,  8) : Block.BlockInfo("block_diamond", 1, 1),
    ( 1,  9) : Block.BlockInfo("block_emerald", 1, 1),
    ( 1, 12) : Block.BlockInfo("mushroom_red", 1, 1),
    ( 1, 13) : Block.BlockInfo("mushroom_brown", 1, 1),
    ( 1, 14) : Block.BlockInfo("sapling_birch", 1, 1),
    ( 2,  0) : Block.BlockInfo("ore_gold", 1, 1),
    ( 2,  1) : Block.BlockInfo("ore_iron", 1, 1),
    ( 2,  2) : Block.BlockInfo("ore_coal", 1, 1),
    ( 2,  3) : Block.BlockInfo("bookcase", 1, 1),
    ( 2,  4) : Block.BlockInfo("cobble_mossy", 1, 1),
    ( 2,  5) : Block.BlockInfo("obsidian", 1, 1),
    ( 2,  6) : Block.BlockInfo("grass_1", 1, 1),
    ( 2,  7) : Block.BlockInfo("grass_2", 1, 1),
    ( 2,  8) : Block.BlockInfo("grass_3", 1, 1),
    ( 2,  9) : Block.BlockInfo("decorative_thing", 1, 1),
    ( 2, 11) : Block.BlockInfo("crafting_bench_top", 1, 1),
    ( 2, 12) : Block.BlockInfo("furnace_front_off", 1, 1),
    ( 2, 13) : Block.BlockInfo("furnace_back", 1, 1),
    ( 2, 14) : Block.BlockInfo("dispenser_face", 1, 1),
    ( 3,  0) : Block.BlockInfo("sponge", 1, 1),
    ( 3,  1) : Block.BlockInfo("glass", 1, 1),
    ( 3,  2) : Block.BlockInfo("ore_diamond", 1, 1),
    ( 3,  3) : Block.BlockInfo("ore_redstone", 1, 1),
    ( 3,  4) : Block.BlockInfo("leaves_1", 1, 1),
    ( 3,  5) : Block.BlockInfo("leaves_2", 1, 1),
    ( 3,  6) : Block.BlockInfo("stone_brick", 1, 1),
    ( 3,  7) : Block.BlockInfo("fern_1", 1, 1),
    ( 3,  8) : Block.BlockInfo("fern_2", 1, 1),
    ( 3, 11) : Block.BlockInfo("crafting_bench_side1", 1, 1),
    ( 3, 12) : Block.BlockInfo("crafting_bench_side2", 1, 1),
    ( 3, 13) : Block.BlockInfo("furnace_front_on", 1, 1),
    ( 3, 14) : Block.BlockInfo("dispenser_top_bottom", 1, 1),
    ( 3, 15) : Block.BlockInfo("sapling_spruce", 1, 1),
    ( 4,  0) : Block.BlockInfo("wool_white", 1, 1),
    ( 4,  1) : Block.BlockInfo("spawner", 1, 1),
    ( 4,  2) : Block.BlockInfo("snow", 1, 1),
    ( 4,  3) : Block.BlockInfo("ice", 1, 1),
    ( 4,  4) : Block.BlockInfo("dirt_snow", 1, 1),
    ( 4,  5) : Block.BlockInfo("cactus_top", 1, 1),
    ( 4,  6) : Block.BlockInfo("cactus_side", 1, 1),
    ( 4,  7) : Block.BlockInfo("cactus_cross", 1, 1),
    ( 4,  8) : Block.BlockInfo("clay", 1, 1),
    ( 4,  9) : Block.BlockInfo("reeds", 1, 1),
    ( 4, 10) : Block.BlockInfo("record_player_bottom_sides", 1, 1),
    ( 4, 11) : Block.BlockInfo("record_player_top", 1, 1),
    ( 4, 12) : Block.BlockInfo("lily_pad", 1, 1),
    ( 4, 13) : Block.BlockInfo("unknown_1", 1, 1),
    ( 4, 14) : Block.BlockInfo("unknown_2", 1, 1),
    ( 4, 15) : Block.BlockInfo("sapling_jungle", 1, 1),
    ( 5,  0) : Block.BlockInfo("torch", 1, 1),
    ( 5,  1) : Block.BlockInfo("door_wooden", 1, 2),
    ( 5,  2) : Block.BlockInfo("door_iron", 1, 2),
    ( 5,  3) : Block.BlockInfo("ladder", 1, 1),
    ( 5,  4) : Block.BlockInfo("hatch", 1, 1),
    ( 5,  5) : Block.BlockInfo("iron_bars", 1, 1),
    ( 5,  6) : Block.BlockInfo("soil_wet", 1, 1),
    ( 5,  7) : Block.BlockInfo("soil_dry", 1, 1),
    ( 5,  8) : Block.BlockInfo("wheat_1", 1, 1),
    ( 5,  9) : Block.BlockInfo("wheat_2", 1, 1),
    ( 5, 10) : Block.BlockInfo("wheat_3", 1, 1),
    ( 5, 11) : Block.BlockInfo("wheat_4", 1, 1),
    ( 5, 12) : Block.BlockInfo("wheat_5", 1, 1),
    ( 5, 13) : Block.BlockInfo("wheat_6", 1, 1),
    ( 5, 14) : Block.BlockInfo("wheat_7", 1, 1),
    ( 5, 15) : Block.BlockInfo("wheat_8", 1, 1),
    ( 6,  0) : Block.BlockInfo("lever", 1, 1),
    ( 6,  3) : Block.BlockInfo("redstone_torch_on", 1, 1),
    ( 6,  4) : Block.BlockInfo("stone_mossy_1", 1, 1),
    ( 6,  5) : Block.BlockInfo("stone_mossy_2", 1, 1),
    ( 6,  6) : Block.BlockInfo("pumpkin_top", 1, 1),
    ( 6,  7) : Block.BlockInfo("netherrack", 1, 1),
    ( 6,  8) : Block.BlockInfo("soulsand", 1, 1),
    ( 6,  9) : Block.BlockInfo("glowstone", 1, 1),
    ( 6, 10) : Block.BlockInfo("piston_top_sticky", 1, 1),
    ( 6, 11) : Block.BlockInfo("piston_top", 1, 1),
    ( 6, 12) : Block.BlockInfo("piston_side", 1, 1),
    ( 6, 13) : Block.BlockInfo("piston_bottom", 1, 1),
    ( 6, 14) : Block.BlockInfo("piston_base", 1, 1),
    ( 6, 15) : Block.BlockInfo("stem_straight", 1, 1),
    ( 7,  0) : Block.BlockInfo("rail_turn", 1, 1),
    ( 7,  1) : Block.BlockInfo("wool_black", 1, 1),
    ( 7,  2) : Block.BlockInfo("wool_gray", 1, 1),
    ( 7,  3) : Block.BlockInfo("redstone_torch_off", 1, 1),
    ( 7,  4) : Block.BlockInfo("wood_side_spruce", 1, 1),
    ( 7,  5) : Block.BlockInfo("wood_side_birch", 1, 1),
    ( 7,  6) : Block.BlockInfo("pumpkin_side_1", 1, 1),
    ( 7,  7) : Block.BlockInfo("pumpkin_side_2", 1, 1),
    ( 7,  8) : Block.BlockInfo("pumpkin_face", 1, 1),
    ( 7,  9) : Block.BlockInfo("cake_top", 1, 1),
    ( 7, 10) : Block.BlockInfo("cake_side_outer", 1, 1),
    ( 7, 11) : Block.BlockInfo("cake_side_inner", 1, 1),
    ( 7, 12) : Block.BlockInfo("cake_bottom", 1, 1),
    ( 7, 13) : Block.BlockInfo("unknown_3", 1, 1),
    ( 7, 14) : Block.BlockInfo("unknown_4", 1, 1),
    ( 7, 15) : Block.BlockInfo("stem_bent", 1, 1),
    ( 8,  0) : Block.BlockInfo("rail", 1, 1),
    ( 8,  1) : Block.BlockInfo("wool_red", 1, 1),
    ( 8,  2) : Block.BlockInfo("wool_pink", 1, 1),
    ( 8,  3) : Block.BlockInfo("redstone_repeater_off", 1, 1),
    ( 8,  4) : Block.BlockInfo("leaves_3", 1, 1),
    ( 8,  5) : Block.BlockInfo("leaves_4", 1, 1),
    ( 8,  6) : Block.BlockInfo("bed_top", 2, 1),
    ( 8,  8) : Block.BlockInfo("mellon_side", 1, 1),
    ( 8,  9) : Block.BlockInfo("mellon_top", 1, 1),
    ( 8, 10) : Block.BlockInfo("cauldron_top", 1, 1),
    ( 8, 11) : Block.BlockInfo("cauldron_bottom", 1, 1),
    ( 8, 12) : Block.BlockInfo("cake_whole", 1, 1),
    ( 8, 13) : Block.BlockInfo("unknown_5", 1, 1),
    ( 8, 14) : Block.BlockInfo("unknown_6", 1, 1),
    ( 8, 15) : Block.BlockInfo("vines", 1, 1),
    ( 9,  0) : Block.BlockInfo("block_lapis", 1, 1),
    ( 9,  1) : Block.BlockInfo("wool_green_dark", 1, 1),
    ( 9,  2) : Block.BlockInfo("wool_green_light", 1, 1),
    ( 9,  3) : Block.BlockInfo("redstone_repeater_on", 1, 1),
    ( 9,  4) : Block.BlockInfo("unknown_7", 1, 1),
    ( 9,  5) : Block.BlockInfo("bed_end", 1, 1),
    ( 9,  6) : Block.BlockInfo("bed_side", 2, 1),
    ( 9,  8) : Block.BlockInfo("bed_head", 1, 1),
    ( 9,  9) : Block.BlockInfo("wood_jungle", 1, 1),
    ( 9, 10) : Block.BlockInfo("cauldron_side", 1, 1),
    ( 9, 11) : Block.BlockInfo("cauldron_feet", 1, 1),
    ( 9, 12) : Block.BlockInfo("brewing_base", 1, 1),
    ( 9, 13) : Block.BlockInfo("brewing_stand", 1, 1),
    ( 9, 14) : Block.BlockInfo("unknown_12", 1, 1),
    ( 9, 15) : Block.BlockInfo("unknown_13", 1, 1),
    (10,  0) : Block.BlockInfo("ore_lapis", 1, 1),
    (10,  1) : Block.BlockInfo("wool_brown", 1, 1),
    (10,  2) : Block.BlockInfo("wool_yellow", 1, 1),
    (10,  3) : Block.BlockInfo("rail_powered_off", 1, 1),
    (10,  4) : Block.BlockInfo("redstone_plus", 1, 1),
    (10,  5) : Block.BlockInfo("redstone_straight", 1, 1),
    (10,  6) : Block.BlockInfo("enchanting_table_top", 1, 1),
    (10,  7) : Block.BlockInfo("unknown_8", 1, 1),
    (10,  8) : Block.BlockInfo("cocoa_beans_3", 1, 1),
    (10,  9) : Block.BlockInfo("cocoa_beans_2", 1, 1),
    (10, 10) : Block.BlockInfo("cocoa_beans_1", 1, 1),
    (10, 11) : Block.BlockInfo("ore_emerald", 1, 1),
    (10, 12) : Block.BlockInfo("tripwire_post", 1, 1),
    (10, 13) : Block.BlockInfo("tripwire", 1, 1),
    (10, 14) : Block.BlockInfo("ender_thingy", 1, 1),
    (10, 15) : Block.BlockInfo("endstone", 1, 1),
    (11,  0) : Block.BlockInfo("sandstone_1", 1, 1),
    (11,  1) : Block.BlockInfo("wool_blue_dark", 1, 1),
    (11,  2) : Block.BlockInfo("wool_blue_light", 1, 1),
    (11,  3) : Block.BlockInfo("rail_powered_on", 1, 1),
    (11,  6) : Block.BlockInfo("enchanting_table_side", 1, 1),
    (11,  7) : Block.BlockInfo("enchanting_table_bottom", 1, 1),
    (11,  8) : Block.BlockInfo("unknown_9", 1, 1),
    (11,  9) : Block.BlockInfo("unknown_10", 1, 1),
    (11, 10) : Block.BlockInfo("unknown_11", 1, 1),
    (12,  0) : Block.BlockInfo("sandstone_2", 1, 1),
    (12,  1) : Block.BlockInfo("wool_purple_dark", 1, 1),
    (12,  2) : Block.BlockInfo("wool_purple_light", 1, 1),
    (12,  3) : Block.BlockInfo("rail_detector", 1, 1),
    (12,  4) : Block.BlockInfo("leaves_5", 1, 1),
    (12,  5) : Block.BlockInfo("leaves_6", 1, 1),
    (12,  6) : Block.BlockInfo("planks_spruce", 1, 1),
    (12,  7) : Block.BlockInfo("planks_jungle", 1, 1),
    (12,  8) : Block.BlockInfo("veggies_1", 1, 1),
    (12,  9) : Block.BlockInfo("veggies_2", 1, 1),
    (12, 10) : Block.BlockInfo("veggies_3", 1, 1),
    (12, 11) : Block.BlockInfo("carrots", 1, 1),
    (12, 12) : Block.BlockInfo("potatoes", 1, 1),
    (13,  0) : Block.BlockInfo("sandstone_3", 1, 1),
    (13,  1) : Block.BlockInfo("wool_aqua", 1, 1),
    (13,  2) : Block.BlockInfo("wool_orange", 1, 1),
    (13,  3) : Block.BlockInfo("redstone_lamp_off", 1, 1),
    (13,  4) : Block.BlockInfo("redstone_lamp_on", 1, 1),
    (13,  5) : Block.BlockInfo("unknown_14", 1, 1),
    (13,  6) : Block.BlockInfo("planks_birch", 1, 1),
    (13,  7) : Block.BlockInfo("anvil_body", 1, 1),
    (13,  8) : Block.BlockInfo("anvil_1", 1, 1),
    (14,  0) : Block.BlockInfo("nether_brick", 1, 1),
    (14,  1) : Block.BlockInfo("wool_gray_light", 1, 1),
    (14,  2) : Block.BlockInfo("netherwart_1", 1, 1),
    (14,  3) : Block.BlockInfo("netherwart_2", 1, 1),
    (14,  4) : Block.BlockInfo("netherwart_3", 1, 1),
    (14,  5) : Block.BlockInfo("sandstone_chiseled", 1, 1),
    (14,  6) : Block.BlockInfo("sandstone_smooth", 1, 1),
    (14,  7) : Block.BlockInfo("anvil_2", 1, 1),
    (14,  8) : Block.BlockInfo("anvil_3", 1, 1),
    (14, 10) : Block.BlockInfo("leaves_7", 1, 1),
    (14, 11) : Block.BlockInfo("leaves_8", 1, 1),
    (15,  0) : Block.BlockInfo("cracks_ 1", 1, 1),
    (15,  1) : Block.BlockInfo("cracks_ 2", 1, 1),
    (15,  2) : Block.BlockInfo("cracks_ 3", 1, 1),
    (15,  3) : Block.BlockInfo("cracks_ 4", 1, 1),
    (15,  4) : Block.BlockInfo("cracks_ 5", 1, 1),
    (15,  5) : Block.BlockInfo("cracks_ 6", 1, 1),
    (15,  6) : Block.BlockInfo("cracks_ 7", 1, 1),
    (15,  7) : Block.BlockInfo("cracks_ 8", 1, 1),
    (15,  8) : Block.BlockInfo("cracks_ 9", 1, 1),
    (15,  9) : Block.BlockInfo("cracks_10", 1, 1)
    }
